---
version: '3'
services:
  valkey:
    image: docker.io/valkey/valkey
    command: valkey-server --bind 127.0.0.1 --loglevel warning
    network_mode: host
    volumes:
      - ./system/valkey:/data
    restart: always
