DNS_PROVIDERS = {
    "allinkl": [
        {"ALL_INKL_LOGIN": "KAS login"},
        {"ALL_INKL_PASSWORD": "KAS password"},
        {"ALL_INKL_HTTP_TIMEOUT": "API request timeout"},
        {"ALL_INKL_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"ALL_INKL_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
    ],
    "arvancloud": [
        {"ARVANCLOUD_API_KEY": "API key"},
        {"ARVANCLOUD_HTTP_TIMEOUT": "API request timeout"},
        {"ARVANCLOUD_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"ARVANCLOUD_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"ARVANCLOUD_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "autodns": [
        {"AUTODNS_API_PASSWORD": "User Password"},
        {"AUTODNS_API_USER": "Username"},
        {"AUTODNS_CONTEXT": "API context (4 for production, 1 for testing. Defaults to 4)"},
        {"AUTODNS_HTTP_TIMEOUT": "API request timeout, defaults to 30 seconds"},
        {"AUTODNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"AUTODNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"AUTODNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "azure": [
        {"AZURE_CLIENT_ID": "Client ID"},
        {"AZURE_CLIENT_SECRET": "Client secret"},
        {"AZURE_ENVIRONMENT": "Azure environment, one of: public, usgovernment, and china"},
        {"AZURE_RESOURCE_GROUP": "DNS zone resource group"},
        {"AZURE_SUBSCRIPTION_ID": "DNS zone subscription ID"},
        {"AZURE_TENANT_ID": "Tenant ID"},
        {"AZURE_METADATA_ENDPOINT": "Metadata Service endpoint URL"},
        {"AZURE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"AZURE_PRIVATE_ZONE": "Set to true to use Azure Private DNS Zones and not public"},
        {"AZURE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"AZURE_TTL": "The TTL of the TXT record used for the DNS challenge"},
        {"AZURE_ZONE_NAME": "Zone name to use inside Azure DNS service to add the TXT record in"},
    ],
    "bindman": [
        {"BINDMAN_MANAGER_ADDRESS": "The server URL, should have scheme, hostname, and port (if required) of the Bindman-DNS Manager server"},
        {"BINDMAN_HTTP_TIMEOUT": "API request timeout"},
        {"BINDMAN_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"BINDMAN_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
    ],
    "bluecat": [
        {"BLUECAT_CONFIG_NAME": "Configuration name"},
        {"BLUECAT_DNS_VIEW": "External DNS View Name"},
        {"BLUECAT_PASSWORD": "API password"},
        {"BLUECAT_SERVER_URL": "The server URL, should have scheme, hostname, and port (if required) of the authoritative Bluecat BAM serve"},
        {"BLUECAT_USER_NAME": "API username"},
        {"BLUECAT_HTTP_TIMEOUT": "API request timeout"},
        {"BLUECAT_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"BLUECAT_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"BLUECAT_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "brandit": [
        {"BRANDIT_API_KEY": "The API key"},
        {"BRANDIT_API_USERNAME": "The API username"},
        {"BRANDIT_HTTP_TIMEOUT": "API request timeout"},
        {"BRANDIT_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"BRANDIT_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"BRANDIT_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "bunny": [
        {"BUNNY_API_KEY": "API key"},
        {"BUNNY_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"BUNNY_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"BUNNY_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "checkdomain": [
        {"CHECKDOMAIN_TOKEN": "API token"},
        {"CHECKDOMAIN_HTTP_TIMEOUT": "API request timeout, defaults to 30 seconds"},
        {"CHECKDOMAIN_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CHECKDOMAIN_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CHECKDOMAIN_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "civo": [
        {"CIVO_TOKEN": "Authentication token"},
        {"CIVO_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CIVO_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CIVO_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "clouddns": [
        {"CLOUDDNS_CLIENT_ID": "Client ID"},
        {"CLOUDDNS_EMAIL": "Account email"},
        {"CLOUDDNS_PASSWORD": "Account password"},
        {"CLOUDDNS_HTTP_TIMEOUT": "API request timeout"},
        {"CLOUDDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CLOUDDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CLOUDDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "cloudflare": [
        {"CLOUDFLARE_API_KEY": "Alias to CF_API_KEY"},
        {"CLOUDFLARE_DNS_API_TOKEN": "Alias to CF_DNS_API_TOKEN"},
        {"CLOUDFLARE_EMAIL": "Alias to CF_API_EMAIL"},
        {"CLOUDFLARE_ZONE_API_TOKEN": "Alias to CF_ZONE_API_TOKEN"},
        {"CLOUDFLARE_HTTP_TIMEOUT": "API request timeout"},
        {"CLOUDFLARE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CLOUDFLARE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CLOUDFLARE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "cloudns": [
        {"CLOUDNS_AUTH_ID": "The API user ID"},
        {"CLOUDNS_AUTH_PASSWORD": "The password for API user ID"},
        {"CLOUDNS_HTTP_TIMEOUT": "API request timeout"},
        {"CLOUDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CLOUDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CLOUDNS_SUB_AUTH_ID": "The API sub user ID"},
        {"CLOUDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "cloudru": [
        {"CLOUDRU_KEY_ID": "Key ID (login)"},
        {"CLOUDRU_SECRET": "Key Secret"},
        {"CLOUDRU_SERVICE_INSTANCE_ID": "Service Instance ID (parentId)"},
        {"CLOUDRU_HTTP_TIMEOUT": "API request timeout"},
        {"CLOUDRU_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CLOUDRU_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CLOUDRU_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"CLOUDRU_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "cloudxns": [
        {"CLOUDXNS_API_KEY": "The API key"},
        {"CLOUDXNS_SECRET_KEY": "The API secret key"},
        {"CLOUDXNS_HTTP_TIMEOUT": "API request timeout"},
        {"CLOUDXNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CLOUDXNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CLOUDXNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "conoha": [
        {"CONOHA_API_PASSWORD": "The API password"},
        {"CONOHA_API_USERNAME": "The API username"},
        {"CONOHA_TENANT_ID": "Tenant ID"},
        {"CONOHA_HTTP_TIMEOUT": "API request timeout"},
        {"CONOHA_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CONOHA_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CONOHA_REGION": "The region"},
        {"CONOHA_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "constellix": [
        {"CONSTELLIX_API_KEY": "User API key"},
        {"CONSTELLIX_SECRET_KEY": "User secret key"},
        {"CONSTELLIX_HTTP_TIMEOUT": "API request timeout"},
        {"CONSTELLIX_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"CONSTELLIX_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"CONSTELLIX_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "derak": [
        {"DERAK_API_KEY": "The API key"},
        {"DERAK_HTTP_TIMEOUT": "API request timeout"},
        {"DERAK_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DERAK_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DERAK_TTL": "The TTL of the TXT record used for the DNS challenge"},
        {"DERAK_WEBSITE_ID": "Force the zone/website ID"},
    ],
    "desec": [
        {"DESEC_TOKEN": "Domain token"},
        {"DESEC_HTTP_TIMEOUT": "API request timeout"},
        {"DESEC_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DESEC_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DESEC_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "designate": [
        {"DESIGNATE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DESIGNATE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DESIGNATE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "dnshomede": [
        {"DNSHOMEDE_CREDENTIALS": "Comma-separated list of domain:password credential pairs"}
    ],
    "dnsimple": [
        {"DNSIMPLE_OAUTH_TOKEN": "OAuth token"},
        {"DNSIMPLE_BASE_URL": "API endpoint URL"},
        {"DNSIMPLE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DNSIMPLE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DNSIMPLE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "dnsmadeeasy": [
        {"DNSMADEEASY_API_KEY": "The API key"},
        {"DNSMADEEASY_API_SECRET": "The API Secret key"},
        {"DNSMADEEASY_HTTP_TIMEOUT": "API request timeout"},
        {"DNSMADEEASY_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DNSMADEEASY_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DNSMADEEASY_SANDBOX": "Activate the sandbox (boolean)"},
        {"DNSMADEEASY_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "dnspod": [
        {"DNSPOD_API_KEY": "The user token"},
        {"DNSPOD_HTTP_TIMEOUT": "API request timeout"},
        {"DNSPOD_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DNSPOD_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DNSPOD_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "dode": [
        {"DODE_TOKEN": "API token"},
        {"DODE_HTTP_TIMEOUT": "API request timeout"},
        {"DODE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DODE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DODE_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"DODE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "domeneshop": [
        {"DOMENESHOP_API_SECRET": "API secret"},
        {"DOMENESHOP_API_TOKEN": "API token"},
        {"DOMENESHOP_HTTP_TIMEOUT": "API request timeout"},
        {"DOMENESHOP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DOMENESHOP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
    ],
    "dreamhost": [
        {"DREAMHOST_API_KEY": "The API key"},
        {"DREAMHOST_HTTP_TIMEOUT": "API request timeout"},
        {"DREAMHOST_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DREAMHOST_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DREAMHOST_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "duckdns": [
        {"DUCKDNS_TOKEN": "Account token"},
        {"DUCKDNS_HTTP_TIMEOUT": "API request timeout"},
        {"DUCKDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DUCKDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DUCKDNS_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"DUCKDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "dyn": [
        {"DYN_CUSTOMER_NAME": "Customer name"},
        {"DYN_PASSWORD": "Password"},
        {"DYN_USER_NAME": "User name"},
        {"DYN_HTTP_TIMEOUT": "API request timeout"},
        {"DYN_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DYN_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DYN_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "dynu": [
        {"DYNU_API_KEY": "API key"},
        {"DYNU_HTTP_TIMEOUT": "API request timeout"},
        {"DYNU_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"DYNU_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"DYNU_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "easydns": [
        {"EASYDNS_KEY": "API Key"},
        {"EASYDNS_TOKEN": "API Token"},
        {"EASYDNS_ENDPOINT": "The endpoint URL of the API Server"},
        {"EASYDNS_HTTP_TIMEOUT": "API request timeout"},
        {"EASYDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"EASYDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"EASYDNS_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"EASYDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "efficientip": [
        {"EFFICIENTIP_DNS_NAME": "DNS name (ex: dns.smart)"},
        {"EFFICIENTIP_HOSTNAME": "Hostname (ex: foo.example.com)"},
        {"EFFICIENTIP_PASSWORD": "Password"},
        {"EFFICIENTIP_USERNAME": "Username"},
        {"EFFICIENTIP_HTTP_TIMEOUT": "API request timeout"},
        {"EFFICIENTIP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"EFFICIENTIP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"EFFICIENTIP_TTL": "The TTL of the TXT record used for the DNS challenge"},
        {"EFFICIENTIP_VIEW_NAME": "View name (ex: external)"},
    ],
    "epik": [
        {"EPIK_HTTP_TIMEOUT": "API request timeout"},
        {"EPIK_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"EPIK_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"EPIK_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "exoscale": [
        {"EXOSCALE_API_KEY": "API key"},
        {"EXOSCALE_API_SECRET": "API secret"},
        {"EXOSCALE_API_ZONE": "API zone"},
        {"EXOSCALE_ENDPOINT": "API endpoint URL"},
        {"EXOSCALE_HTTP_TIMEOUT": "API request timeout"},
        {"EXOSCALE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"EXOSCALE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"EXOSCALE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "freemyip": [
        {"FREEMYIP_TOKEN": "Account token"},
        {"FREEMYIP_HTTP_TIMEOUT": "API request timeout"},
        {"FREEMYIP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"FREEMYIP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"FREEMYIP_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"FREEMYIP_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "gandi": [
        {"GANDI_API_KEY": "API key"},
        {"GANDI_HTTP_TIMEOUT": "API request timeout"},
        {"GANDI_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"GANDI_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"GANDI_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "gandiv5": [
        {"GANDIV5_API_KEY": "API key"},
        {"GANDIV5_HTTP_TIMEOUT": "API request timeout"},
        {"GANDIV5_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"GANDIV5_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"GANDIV5_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "gcore": [
        {"GCORE_HTTP_TIMEOUT": "API request timeout"},
        {"GCORE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"GCORE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"GCORE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "glesys": [
        {"GLESYS_API_KEY": "API key"},
        {"GLESYS_API_USER": "API user"},
        {"GLESYS_HTTP_TIMEOUT": "API request timeout"},
        {"GLESYS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"GLESYS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"GLESYS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "godaddy": [
        {"GODADDY_API_KEY": "API key"},
        {"GODADDY_API_SECRET": "API secret"},
        {"GODADDY_HTTP_TIMEOUT": "API request timeout"},
        {"GODADDY_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"GODADDY_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"GODADDY_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "hetzner": [
        {"HETZNER_API_KEY": "API key"},
        {"HETZNER_HTTP_TIMEOUT": "API request timeout"},
        {"HETZNER_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"HETZNER_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"HETZNER_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "hostingde": [
        {"HOSTINGDE_API_KEY": "API key"},
        {"HOSTINGDE_HTTP_TIMEOUT": "API request timeout"},
        {"HOSTINGDE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"HOSTINGDE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"HOSTINGDE_TTL": "The TTL of the TXT record used for the DNS challenge"},
        {"HOSTINGDE_ZONE_NAME": "Zone name in ACE format"},
    ],
    "hosttech": [
        {"HOSTTECH_API_KEY": "API login"},
        {"HOSTTECH_PASSWORD": "API password"},
        {"HOSTTECH_HTTP_TIMEOUT": "API request timeout"},
        {"HOSTTECH_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"HOSTTECH_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"HOSTTECH_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "httpreq": [
        {"HTTPREQ_ENDPOINT": "The URL of the server"},
        {"HTTPREQ_MODE": "'RAW', none"},
        {"HTTPREQ_HTTP_TIMEOUT": "API request timeout"},
        {"HTTPREQ_PASSWORD": "Basic authentication password"},
        {"HTTPREQ_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"HTTPREQ_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"HTTPREQ_USERNAME": "Basic authentication username"},
    ],
    "hurricane": [
        {"HURRICANE_TOKENS": "TXT record names and tokens"}
    ],
    "hyperone": [
        {"HYPERONE_LOCATION_ID": "Specifies location (region) to be used in API calls. (default pl-waw-1)"},
        {"HYPERONE_PASSPORT_LOCATION": "Allows to pass custom passport file location (default ~/.h1/passport.json)"},
        {"HYPERONE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"HYPERONE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"HYPERONE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "iij": [
        {"IIJ_API_ACCESS_KEY": "API access key"},
        {"IIJ_API_SECRET_KEY": "API secret key"},
        {"IIJ_DO_SERVICE_CODE": "DO service code"},
        {"IIJ_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"IIJ_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"IIJ_TTL": "The TTL of the TXT record used for the DNS challenge"},
        {"IIJ_DPF_API_TOKEN": "API token"},
        {"IIJ_DPF_DPM_SERVICE_CODE": "IIJ Managed DNS Service's service code"},
        {"IIJ_DPF_POLLING_INTERVAL": "Time between DNS propagation check, defaults to 5 second"},
        {"IIJ_DPF_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation, defaults to 660 second"},
        {"IIJ_DPF_TTL": "The TTL of the TXT record used for the DNS challenge, default to 300"},
    ],
    "infoblox": [
        {"INFOBLOX_HOST": "Host URI"},
        {"INFOBLOX_PASSWORD": "Account Password"},
        {"INFOBLOX_USERNAME": "Account Username"},
        {"INFOBLOX_DNS_VIEW": "The view for the TXT records, default: External"},
        {"INFOBLOX_HTTP_TIMEOUT": "HTTP request timeout"},
        {"INFOBLOX_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"INFOBLOX_PORT": "The port for the infoblox grid manager, default: 443"},
        {"INFOBLOX_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"INFOBLOX_SSL_VERIFY": "Whether or not to verify the TLS certificate, default: true"},
        {"INFOBLOX_TTL": "The TTL of the TXT record used for the DNS challenge"},
        {"INFOBLOX_WAPI_VERSION": "The version of WAPI being used, default: 2.11"},
    ],
    "infomaniak": [
        {"INFOMANIAK_ACCESS_TOKEN": "Access token"},
        {"INFOMANIAK_HTTP_TIMEOUT": "API request timeout"},
        {"INFOMANIAK_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"INFOMANIAK_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"INFOMANIAK_TTL": "The TTL of the TXT record used for the DNS challenge in seconds"},
    ],
    "inwx": [
        {"INWX_PASSWORD": "Password"},
        {"INWX_USERNAME": "Username"},
        {"INWX_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"INWX_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation (default 360s)"},
        {"INWX_SANDBOX": "Activate the sandbox (boolean)"},
        {"INWX_SHARED_SECRET": "shared secret related to 2FA"},
        {"INWX_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "ionos": [
        {"IONOS_HTTP_TIMEOUT": "API request timeout"},
        {"IONOS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"IONOS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"IONOS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "ipv64": [
        {"IPV64_API_KEY": "Account API Key"},
        {"IPV64_HTTP_TIMEOUT": "API request timeout"},
        {"IPV64_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"IPV64_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"IPV64_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"IPV64_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "iwantmyname": [
        {"IWANTMYNAME_PASSWORD": "API password"},
        {"IWANTMYNAME_USERNAME": "API username"},
        {"IWANTMYNAME_HTTP_TIMEOUT": "API request timeout"},
        {"IWANTMYNAME_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"IWANTMYNAME_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"IWANTMYNAME_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "joker": [
        {"JOKER_API_KEY": "API key (only with DMAPI mode)"},
        {"JOKER_API_MODE": "'DMAPI' or 'SVC'. DMAPI is for resellers accounts. (Default: DMAPI)"},
        {"JOKER_PASSWORD": "Joker.com password"},
        {"JOKER_USERNAME": "Joker.com username"},
        {"JOKER_HTTP_TIMEOUT": "API request timeout"},
        {"JOKER_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"JOKER_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"JOKER_SEQUENCE_INTERVAL": "Time between sequential requests (only with 'SVC' mode)"},
        {"JOKER_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "liara": [
        {"LIARA_API_KEY": "The API key"},
        {"LIARA_HTTP_TIMEOUT": "API request timeout"},
        {"LIARA_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"LIARA_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"LIARA_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "lightsail": [
        {"LIGHTSAIL_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"LIGHTSAIL_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
    ],
    "linode": [
        {"LINODE_TOKEN": "API token"},
        {"LINODE_HTTP_TIMEOUT": "API request timeout"},
        {"LINODE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"LINODE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"LINODE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "loopia": [
        {"LOOPIA_API_PASSWORD": "API password"},
        {"LOOPIA_API_USER": "API username"},
        {"LOOPIA_HTTP_TIMEOUT": "API request timeout"},
        {"LOOPIA_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"LOOPIA_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"LOOPIA_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "luadns": [
        {"LUADNS_API_TOKEN": "API token"},
        {"LUADNS_API_USERNAME": "Username (your email)"},
        {"LUADNS_HTTP_TIMEOUT": "API request timeout"},
        {"LUADNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"LUADNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"LUADNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "metaname": [
        {"METANAME_ACCOUNT_REFERENCE": "The four-digit reference of a Metaname account"},
        {"METANAME_API_KEY": "API Key"},
        {"METANAME_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"METANAME_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"METANAME_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "mydnsjp": [
        {"MYDNSJP_MASTER_ID": "Master ID"},
        {"MYDNSJP_PASSWORD": "Password"},
        {"MYDNSJP_HTTP_TIMEOUT": "API request timeout"},
        {"MYDNSJP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"MYDNSJP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"MYDNSJP_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "mythicbeasts": [
        {"MYTHICBEASTS_PASSWORD": "Password"},
        {"MYTHICBEASTS_USERNAME": "User name"},
        {"MYTHICBEASTS_API_ENDPOINT": "The endpoint for the API (must implement v2)"},
        {"MYTHICBEASTS_AUTH_API_ENDPOINT": "The endpoint for Mythic Beasts' Authentication"},
        {"MYTHICBEASTS_HTTP_TIMEOUT": "API request timeout"},
        {"MYTHICBEASTS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"MYTHICBEASTS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"MYTHICBEASTS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "namecheap": [
        {"NAMECHEAP_API_KEY": "API key"},
        {"NAMECHEAP_API_USER": "API user"},
        {"NAMECHEAP_HTTP_TIMEOUT": "API request timeout"},
        {"NAMECHEAP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NAMECHEAP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NAMECHEAP_SANDBOX": "Activate the sandbox (boolean)"},
        {"NAMECHEAP_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "namesilo": [
        {"NAMESILO_API_KEY": "Client ID"},
        {"NAMESILO_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NAMESILO_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation, it is better to set larger than 15m"},
        {"NAMESILO_TTL": "The TTL of the TXT record used for the DNS challenge, should be in [3600, 2592000]"},
    ],
    "nearlyfreespeech": [
        {"NEARLYFREESPEECH_API_KEY": "API Key for API requests"},
        {"NEARLYFREESPEECH_LOGIN": "Username for API requests"},
        {"NEARLYFREESPEECH_HTTP_TIMEOUT": "API request timeout"},
        {"NEARLYFREESPEECH_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NEARLYFREESPEECH_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NEARLYFREESPEECH_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"NEARLYFREESPEECH_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "netcup": [
        {"NETCUP_API_KEY": "API key"},
        {"NETCUP_API_PASSWORD": "API password"},
        {"NETCUP_CUSTOMER_NUMBER": "Customer number"},
        {"NETCUP_HTTP_TIMEOUT": "API request timeout"},
        {"NETCUP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NETCUP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NETCUP_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "netlify": [
        {"NETLIFY_TOKEN": "Token"},
        {"NETLIFY_HTTP_TIMEOUT": "API request timeout"},
        {"NETLIFY_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NETLIFY_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NETLIFY_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "nicmanager": [
        {"NICMANAGER_API_EMAIL": "Email-based login"},
        {"NICMANAGER_API_LOGIN": "Login, used for Username-based login"},
        {"NICMANAGER_API_PASSWORD": "Password, always required"},
        {"NICMANAGER_API_USERNAME": "Username, used for Username-based login"},
        {"NICMANAGER_API_MODE": "mode: 'anycast' or 'zone' (default: 'anycast')"},
        {"NICMANAGER_API_OTP": "TOTP Secret (optional)"},
        {"NICMANAGER_HTTP_TIMEOUT": "API request timeout"},
        {"NICMANAGER_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NICMANAGER_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NICMANAGER_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "nifcloud": [
        {"NIFCLOUD_ACCESS_KEY_ID": "Access key"},
        {"NIFCLOUD_SECRET_ACCESS_KEY": "Secret access key"},
        {"NIFCLOUD_HTTP_TIMEOUT": "API request timeout"},
        {"NIFCLOUD_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NIFCLOUD_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NIFCLOUD_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "njalla": [
        {"NJALLA_TOKEN": "API token"},
        {"NJALLA_HTTP_TIMEOUT": "API request timeout"},
        {"NJALLA_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NJALLA_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NJALLA_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "nodion": [
        {"NODION_API_TOKEN": "The API token"},
        {"NODION_HTTP_TIMEOUT": "API request timeout"},
        {"NODION_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NODION_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NODION_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "ns1": [
        {"NS1_API_KEY": "API key"},
        {"NS1_HTTP_TIMEOUT": "API request timeout"},
        {"NS1_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"NS1_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"NS1_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "otc": [
        {"OTC_DOMAIN_NAME": "Domain name"},
        {"OTC_IDENTITY_ENDPOINT": "Identity endpoint URL"},
        {"OTC_PASSWORD": "Password"},
        {"OTC_PROJECT_NAME": "Project name"},
        {"OTC_USER_NAME": "User name"},
        {"OTC_HTTP_TIMEOUT": "API request timeout"},
        {"OTC_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"OTC_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"OTC_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "ovh": [
        {"OVH_APPLICATION_KEY": "Application key"},
        {"OVH_APPLICATION_SECRET": "Application secret"},
        {"OVH_CONSUMER_KEY": "Consumer key"},
        {"OVH_ENDPOINT": "Endpoint URL (ovh-eu or ovh-ca)"},
        {"OVH_HTTP_TIMEOUT": "API request timeout"},
        {"OVH_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"OVH_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"OVH_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "pdns": [
        {"PDNS_API_KEY": "API key"},
        {"PDNS_API_URL": "API URL"},
        {"PDNS_HTTP_TIMEOUT": "API request timeout"},
        {"PDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"PDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"PDNS_SERVER_NAME": "Name of the server in the URL, 'localhost' by default"},
        {"PDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "plesk": [
        {"PLESK_PASSWORD": "API password"},
        {"PLESK_USERNAME": "API username"},
        {"PLESK_HTTP_TIMEOUT": "API request timeout"},
        {"PLESK_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"PLESK_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"PLESK_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "porkbun": [
        {"PORKBUN_API_KEY": "API key"},
        {"PORKBUN_SECRET_API_KEY": "secret API key"},
        {"PORKBUN_HTTP_TIMEOUT": "API request timeout"},
        {"PORKBUN_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"PORKBUN_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"PORKBUN_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "rackspace": [
        {"RACKSPACE_API_KEY": "API key"},
        {"RACKSPACE_USER": "API user"},
        {"RACKSPACE_HTTP_TIMEOUT": "API request timeout"},
        {"RACKSPACE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"RACKSPACE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"RACKSPACE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "rcodezero": [
        {"RCODEZERO_API_TOKEN": "API token"},
        {"RCODEZERO_HTTP_TIMEOUT": "API request timeout"},
        {"RCODEZERO_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"RCODEZERO_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"RCODEZERO_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "regru": [
        {"REGRU_PASSWORD": "API password"},
        {"REGRU_USERNAME": "API username"},
        {"REGRU_HTTP_TIMEOUT": "API request timeout"},
        {"REGRU_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"REGRU_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"REGRU_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "rfc2136": [
        {"RFC2136_NAMESERVER": "Network address in the form 'host' or 'host:port'"},
        {"RFC2136_TSIG_KEY": "Name of the secret key as defined in DNS server configuration. To disable TSIG authentication, leave the 'RFC2136_TSIG*' variables unset."},
        {"RFC2136_TSIG_SECRET": "Secret key payload. To disable TSIG authentication, leave the' RFC2136_TSIG*' variables unset."},
        {"RFC2136_DNS_TIMEOUT": "API request timeout"},
        {"RFC2136_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"RFC2136_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"RFC2136_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"RFC2136_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "rimuhosting": [
        {"RIMUHOSTING_API_KEY": "User API key"},
        {"RIMUHOSTING_HTTP_TIMEOUT": "API request timeout"},
        {"RIMUHOSTING_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"RIMUHOSTING_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"RIMUHOSTING_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "safedns": [
        {"SAFEDNS_AUTH_TOKEN": "Authentication token"},
        {"SAFEDNS_HTTP_TIMEOUT": "API request timeout"},
        {"SAFEDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SAFEDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SAFEDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "sakuracloud": [
        {"SAKURACLOUD_ACCESS_TOKEN": "Access token"},
        {"SAKURACLOUD_ACCESS_TOKEN_SECRET": "Access token secret"},
        {"SAKURACLOUD_HTTP_TIMEOUT": "API request timeout"},
        {"SAKURACLOUD_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SAKURACLOUD_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SAKURACLOUD_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "scaleway": [
        {"SCALEWAY_API_TOKEN": "API token"},
        {"SCALEWAY_PROJECT_ID": "Project to use (optional)"},
        {"SCALEWAY_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SCALEWAY_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SCALEWAY_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "selectel": [
        {"SELECTEL_API_TOKEN": "API token"},
        {"SELECTEL_BASE_URL": "API endpoint URL"},
        {"SELECTEL_HTTP_TIMEOUT": "API request timeout"},
        {"SELECTEL_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SELECTEL_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SELECTEL_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "servercow": [
        {"SERVERCOW_PASSWORD": "API password"},
        {"SERVERCOW_USERNAME": "API username"},
        {"SERVERCOW_HTTP_TIMEOUT": "API request timeout"},
        {"SERVERCOW_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SERVERCOW_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SERVERCOW_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "simply": [
        {"SIMPLY_ACCOUNT_NAME": "Account name"},
        {"SIMPLY_API_KEY": "API key"},
        {"SIMPLY_HTTP_TIMEOUT": "API request timeout"},
        {"SIMPLY_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SIMPLY_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SIMPLY_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "sonic": [
        {"SONIC_API_KEY": "API Key"},
        {"SONIC_USER_ID": "User ID"},
        {"SONIC_HTTP_TIMEOUT": "API request timeout"},
        {"SONIC_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"SONIC_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"SONIC_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"SONIC_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "stackpath": [
        {"STACKPATH_CLIENT_ID": "Client ID"},
        {"STACKPATH_CLIENT_SECRET": "Client secret"},
        {"STACKPATH_STACK_ID": "Stack ID"},
        {"STACKPATH_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"STACKPATH_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"STACKPATH_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "tencentcloud": [
        {"TENCENTCLOUD_SECRET_ID": "Access key ID"},
        {"TENCENTCLOUD_SECRET_KEY": "Access Key secret"},
        {"TENCENTCLOUD_HTTP_TIMEOUT": "API request timeout"},
        {"TENCENTCLOUD_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"TENCENTCLOUD_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"TENCENTCLOUD_REGION": "Region"},
        {"TENCENTCLOUD_SESSION_TOKEN": "Access Key token"},
        {"TENCENTCLOUD_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "transip": [
        {"TRANSIP_ACCOUNT_NAME": "Account name"},
        {"TRANSIP_PRIVATE_KEY_PATH": "Private key path"},
        {"TRANSIP_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"TRANSIP_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"TRANSIP_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "ultradns": [
        {"ULTRADNS_PASSWORD": "API Password"},
        {"ULTRADNS_USERNAME": "API Username"},
        {"ULTRADNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"ULTRADNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"ULTRADNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "vegadns": [
        {"VEGADNS_URL": "API endpoint URL"},
        {"VEGADNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"VEGADNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"VEGADNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "vercel": [
        {"VERCEL_API_TOKEN": "Authentication token"},
        {"VERCEL_HTTP_TIMEOUT": "API request timeout"},
        {"VERCEL_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"VERCEL_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"VERCEL_TEAM_ID": "Team ID (ex: team_xxxxxxxxxxxxxxxxxxxxxxxx)"},
        {"VERCEL_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "versio": [
        {"VERSIO_PASSWORD": "Basic authentication password"},
        {"VERSIO_USERNAME": "Basic authentication username"},
        {"VERSIO_ENDPOINT": "The endpoint URL of the API Server"},
        {"VERSIO_HTTP_TIMEOUT": "API request timeout"},
        {"VERSIO_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"VERSIO_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"VERSIO_SEQUENCE_INTERVAL": "Time between sequential requests, default 60s"},
        {"VERSIO_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "vinyldns": [
        {"VINYLDNS_ACCESS_KEY": "The VinylDNS API key"},
        {"VINYLDNS_HOST": "The VinylDNS API URL"},
        {"VINYLDNS_SECRET_KEY": "The VinylDNS API Secret key"},
        {"VINYLDNS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"VINYLDNS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"VINYLDNS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "vscale": [
        {"VSCALE_API_TOKEN": "API token"},
        {"VSCALE_BASE_URL": "API endpoint URL"},
        {"VSCALE_HTTP_TIMEOUT": "API request timeout"},
        {"VSCALE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"VSCALE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"VSCALE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "vultr": [
        {"VULTR_API_KEY": "API key"},
        {"VULTR_HTTP_TIMEOUT": "API request timeout"},
        {"VULTR_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"VULTR_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"VULTR_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "websupport": [
        {"WEBSUPPORT_API_KEY": "API key"},
        {"WEBSUPPORT_SECRET": "API secret"},
        {"WEBSUPPORT_HTTP_TIMEOUT": "API request timeout"},
        {"WEBSUPPORT_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"WEBSUPPORT_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"WEBSUPPORT_SEQUENCE_INTERVAL": "Time between sequential requests"},
        {"WEBSUPPORT_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "wedos": [
        {"WEDOS_USERNAME": "Username is the same as for the admin account"},
        {"WEDOS_WAPI_PASSWORD": "Password needs to be generated and IP allowed in the admin interface"},
        {"WEDOS_HTTP_TIMEOUT": "API request timeout"},
        {"WEDOS_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"WEDOS_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"WEDOS_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "zoneee": [
        {"ZONEEE_API_KEY": "API key"},
        {"ZONEEE_API_USER": "API user"},
        {"ZONEEE_ENDPOINT": "API endpoint URL"},
        {"ZONEEE_HTTP_TIMEOUT": "API request timeout"},
        {"ZONEEE_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"ZONEEE_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"ZONEEE_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
    "zonomi": [
        {"ZONOMI_API_KEY": "User API key"},
        {"ZONOMI_HTTP_TIMEOUT": "API request timeout"},
        {"ZONOMI_POLLING_INTERVAL": "Time between DNS propagation check"},
        {"ZONOMI_PROPAGATION_TIMEOUT": "Maximum waiting time for DNS propagation"},
        {"ZONOMI_TTL": "The TTL of the TXT record used for the DNS challenge"},
    ],
}
