load_module "modules/ngx_nchan_module.so";

worker_processes auto;
error_log /dev/fd/1 info;
events {
    worker_connections 768;
}

http {
  upstream redis {
    nchan_redis_storage_mode nostore;
    nchan_redis_nostore_fastpublish on;
    nchan_redis_server 127.0.0.1;
  }
  
  server {
    listen 80 default_server;
    listen [::]:80 default_server;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    ssl_certificate /data/certs/fullchain.pem;
    ssl_certificate_key /data/certs/privkey.pem;

    root /usr/share/nginx;

    server_name _;
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
      text/plain
      text/css
      text/js
      text/javascript
      application/javascript
      application/json
      application/xml
      image/svg+xml;

    # Ggf. noch group channel
    location ~ /sub/user/(\w+) {
      nchan_channel_id "$1";
      nchan_subscriber;
      nchan_redis_pass redis;
      nchan_authorize_request /nchan/auth/$1;
    }

    location ~ /nchan/auth/(\w+)$ {
      proxy_pass http://127.0.0.1:8082;
      proxy_pass_request_body off;
      proxy_redirect http:// $scheme://;
      proxy_set_header Content-Length "";
      proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
      proxy_set_header X-Publisher-Type $nchan_publisher_type;
      proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
      proxy_set_header X-Channel-Id $nchan_channel_id;
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://127.0.0.1:8082;
      proxy_redirect http:// $scheme://;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

  server {
    listen 127.0.0.1:8555;
    server_name internal.pubsub;

    location ~ /pub/user/(\w+)$ {
      nchan_channel_id "$1";
      nchan_publisher;
      nchan_redis_pass redis;
      nchan_message_buffer_length 50;
      nchan_message_timeout 5m;
    }
  }
}
