import json
import os
import re
import redis
import tarfile

from config import defaults, logger
from config.database import *
from datetime import datetime, timezone
from functools import wraps
from io import BytesIO
from pathlib import Path
from pydantic import ValidationError, validate_call
from quart import redirect, request, session
from typing import Literal


def utc_now_as_str():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S%z")


@validate_call
def get_realm_by_hostname(hostname: str):
    try:
        hostname = get_validated_fqdn(hostname)
        realm = r.getex(f"realmdata:{hostname}", ex=300)
        if realm:
            return json.loads(realm)
    except ValueError:
        logger.warning("Could not read a valid hostname from request, using 'default'")
        # "default" never from cache
        hostname = "default"

    with TinyDB("realms/realms.json") as db:
        realm = db.table("realms").get(Query().identity == hostname)
        if not realm:
            realm = db.table("realms").get(Query().default == True)
            if not realm:
                raise Exception("No realm available")

        assert Path(f"realms/databases/{realm['id']}").exists()
        realm.update(
            {
                "path": f"realms/databases/{realm['id']}",
            }
        )
        r.set(f"realmdata:{hostname}", json.dumps(realm), ex=300)
        return realm


@validate_call
def batch(l: list, n: int):
    _l = len(l)
    for ndx in range(0, _l, n):
        yield l[ndx : min(ndx + n, _l)]


@validate_call
def get_validated_fqdn(hostname: str) -> str:
    regex = re.compile(
        r"^((?![-])[-A-Z\d]{1,63}(?<!-)[.])*(?!-)[-A-Z\d]{1,63}(?<!-)?$", re.IGNORECASE
    )
    if len(hostname) > 253:
        raise ValueError(f"{hostname} is too long")
    if regex.match(hostname):
        return hostname
    else:
        raise ValueError(f"{hostname} is not a valid FQDN")


@validate_call
def ensure_list(s: str | list[str] | None) -> list:
    if s:
        if isinstance(s, str):
            return [s]
        if isinstance(s, list):
            return s
    return []


@validate_call
def str_lists_match(x: list[str], y: list[str]) -> bool:
    return sorted(x, key=lambda x: str(x)) == sorted(x, key=lambda x: str(y))


@validate_call
def str_lists_match_unique(x: list[str], y: list[str]) -> bool:
    return set(sorted(x, key=lambda x: str(x))) == set(sorted(y, key=lambda x: str(x)))


@validate_call
def to_unique_sorted_str_list(l: list[str]) -> list:
    _l = [x for x in set(l) if x != ""]
    return sorted(_l, key=lambda x: str(x))


@validate_call
def flatten(l: list[list]):
    return [i for sub_list in l for i in sub_list]


"""
    - errors: list as generated by ValidationError.errors method (list)
      Example list:
      [
        {
            'loc': ('tz',),
            'msg': 'field required',
            'type': 'value_error.missing'
        },
        {
            'loc': ('dt_fmt',),
            'msg': 'field required',
            'type': 'value_error.missing'
        }
      ]

    - status_code: status code to return (integer)
"""


@validate_call
def show_alert(
    type: Literal["genericError", "genericWarning", "genericSuccess"],
    body: str,
    status_code: int,
    title: str,
    message: str,
    triggers: dict = {},
):
    return (
        body,
        status_code,
        {
            "HX-Retarget": "body",
            "HX-Trigger": json.dumps(
                {
                    "showAlert": {
                        type: {
                            "title": title,
                            "message": message,
                        }
                    },
                    **triggers,
                }
            ),
        },
    )


@validate_call
def validation_error(
    errors: list = [], status_code: int = 422, message: str | None = None
):
    locations = []
    if errors:
        for loc in [l.get("loc") for l in errors if l.get("loc")]:
            i = 1
            _location = None
            if len(loc) > 1:
                while len(loc) > i:
                    if not _location:
                        _location = f"{loc[0]}[{loc[1]}]"
                        i = 2
                    else:
                        _location = f"{_location}[{loc[i]}]"
                        i += 1
                locations.append(_location)
            else:
                locations.append(loc)

        error_msgs = [
            l.get("msg").removeprefix("Value error, ") for l in errors if l.get("msg")
        ]
        if not error_msgs:
            error_msgs = ["Provided data could not be validated"]

    if message:
        error_msgs = [message]
    return (
        "",
        status_code,
        {
            "HX-Retarget": "body",
            "HX-Trigger": json.dumps(
                {
                    "showAlert": {
                        "validationError": {
                            "locations": locations,
                            "message": error_msgs,
                        }
                    }
                }
            ),
        },
    )


def user_session_required(fn):
    @wraps(fn)
    async def wrapper(*args, **kwargs):
        if (
            r.getex(f"user:session:{session.get('id', '')}", 30)
            != request.realm_data["id"]
        ):
            try:
                assert Path(f"realms/databases/{request.realm_data['id']}").exists()
            except AssertionError:
                logger.error("Realm ID provided in session data does not exist")
                session.clear()

            with TinyDB(
                **defaults.TINYDB,
                path=request.realm_data["path"],
            ) as db:
                if (
                    db.table("users").get(Query().id == session.get("id", ""))
                    and request.realm_data["id"] == session["realm_id"]
                ):
                    r.set(
                        f"user:session:{session.get('id', '')}",
                        session["realm_id"],
                        ex=30,
                    )
                    return await fn(*args, **kwargs)
        else:
            return await fn(*args, **kwargs)

        if "Hx-Request" in request.headers:
            return show_alert(
                "genericError",
                "",
                401,
                "Authentication required",
                "You need to be authenticated to access this resource",
            )
        else:
            return redirect("/", code=302)

    return wrapper


def realm_access_required(fn):
    @wraps(fn)
    async def wrapper(*args, **kwargs):
        if not kwargs.get("realm_id") or kwargs.get("realm_id") != session.get(
            "realm_id"
        ):
            if "Hx-Request" in request.headers:
                return show_alert(
                    "genericError",
                    "",
                    401,
                    "Realm access required",
                    "You do not have permission to access this realm",
                )
            else:
                return redirect("/", code=302)

        return await fn(*args, **kwargs)

    return wrapper


@validate_call
def string_to_tar_bytes(filename: str, data: str) -> bytes:
    tarinfo = tarfile.TarInfo(filename)
    tarinfo.size = len(data.encode("utf8"))
    out_tar = BytesIO()
    with tarfile.open(fileobj=out_tar, mode="w|") as tf:
        tf.addfile(tarinfo, BytesIO(data.encode("utf8")))
    out_tar.seek(0)
    return out_tar
